FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-cpu.txt requirements.txt
RUN pip3 install --no-cache-dir --timeout 600 uv
RUN uv pip install --system --no-cache -r requirements.txt

COPY . .

ENV INSIGHTFACE_HOME=/app

EXPOSE 8003

CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003", "--workers", "1", "--log-level", "info"]